### ISSUE TITLE
Open issue for discussing the release process

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-release-process#1]
Please feel free to leave any comments or discussions about the release process on this issue

**Comment by ghost** [comment]
Hi, 

Really nice documentation - thanks. I just had a few minor suggestions: 
- In the section on versioning it might be good to provide a link to some background reading on Semantic Versioning to help illustrate why this approach is so useful. 
- In the Development Process and Release Preparation section it would be good to:
  - Refer to Git Flow as the methodology we use and the related guidance in the [development-machine-configuration](https://github.com/nationalarchives/development-machine-configuration) repo
  - Explain that developers should use the supporting functionality in SourceTree for branch creation and merging
- It might be good to emphasise/underline merge in the sentence that reads 'When you **_merge**_ a `feature/` branch into develop could...'

Cheers, 
G

**Comment by grange85** [comment]
Thanks @GTVJones for that - I've added some links as suggested. I'm looking into ways that we can document the merge to develop for easier release documentation.
